import fs from 'node:fs';
import assert from 'node:assert/strict';
import {db} from './load.mjs';
await db.exec(fs.readFileSync(new URL('../../supabase/migrations/20260923091530_fix_tryout_variable_ambiguity.sql',import.meta.url),'utf8'));
const {asUser,id}=await import('./seed.mjs');
await asUser(id(1));
await db.exec(`begin; reset role; insert into tryouts(id,course_id,title,created_by,review_release_mode) values('${id(50)}','${id(12)}','Regression','${id(1)}','immediate');
insert into tryout_questions(id,tryout_id,question_order,question) values('${id(51)}','${id(50)}',1,'Original');`);
await asUser(id(1));
await db.query(`select admin_update_tryout_question($1,'Updated','Explanation',null,null,'Topic','medium',1,array['A','B','C','D'],1)`,[id(51)]);
await db.exec('commit');
assert.equal((await db.query(`select explanation_image_path from tryout_questions where id=$1`,[id(51)])).rows[0].explanation_image_path,null);
await db.exec(`reset role; insert into tryout_attempts(id,tryout_id,profile_id,attempt_number,expires_at,question_order) values('${id(52)}','${id(50)}','${id(3)}',1,now()+interval '1 hour',array['${id(51)}']::uuid[]);`);
await asUser(id(3));
const result=(await db.query(`select get_tryout_attempt($1) data`,[id(52)])).rows[0].data;
assert.equal(result.questions[0].id,id(51));
assert.equal(result.questions[0].question,'Updated');
await asUser(id(5));
await assert.rejects(db.query(`select get_tryout_attempt($1)`,[id(52)]),/tidak ditemukan/);
console.log('PASS Try Out question update, attempt retrieval and ownership');
await db.close();
